export const catsData = [
  {
    emotionTags: ["angry baby"],
    isGif: false,
    image: "angrybaby1.jpg",
    alt: "",
  },
  {
    emotionTags: ["angry baby"],
    isGif: false,
    image: "angrybaby2.jpg",
    alt: "",
  },
  {
    emotionTags: ["angry baby"],
    isGif: false,
    image: "angry3.webp",
    alt: "",
  },
  {
    emotionTags: ["annoyed"],
    isGif: false,
    image: "annoyed1.webp",
    alt: "",
  },
  {
    emotionTags: ["annoyed"],
    isGif: false,
    image: "annoyed2.jpg",
    alt: "",
  },
  {
    emotionTags: ["annoyed"],
    isGif: false,
    image: "annoyed3.jpg",
    alt: "",
  },
  {
    emotionTags: ["resting bitch face"],
    isGif: false,
    image: "bface1.webp",
    alt: "",
  },
  {
    emotionTags: ["resting bitch face"],
    isGif: false,
    image: "bface2.jpg",
    alt: "",
  },
  {
    emotionTags: ["resting bitch face"],
    isGif: false,
    image: "bface3.jpg",
    alt: "",
  },
  {
    emotionTags: ["emoji"],
    isGif: false,
    image: "emoji1.webp",
    alt: "",
  },
  {
    emotionTags: ["emoji"],
    isGif: false,
    image: "emoji2.jpg",
    alt: "",
  },
  {
    emotionTags: ["emoji"],
    isGif: false,
    image: "emoji3.jpg",
    alt: "",
  },
  {
    emotionTags: ["scowl"],
    isGif: false,
    image: "scowl1.jpg",
    alt: "",
  },
  {
    emotionTags: ["scowl"],
    isGif: false,
    image: "scowl2.webp",
    alt: "",
  },
  {
    emotionTags: ["scowl"],
    isGif: false,
    image: "scowl4.jpeg",
    alt: "",
  },
  {
    emotionTags: ["very angry"],
    isGif: false,
    image: "veryangry1.jpg",
    alt: "",
  },
  {
    emotionTags: ["very angry"],
    isGif: true,
    image: "veryangry2.jpg",
    alt: "",
  },
  {
    emotionTags: ["very angry"],
    isGif: false,
    image: "veryangry3.jpg",
    alt: "",
  },
];
